name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: thumbv7-none-eabi
        override: true
    - uses: actions/checkout@v1
    - name: Build
      run: |
        cd firmware/rust-soldering-station/
        cargo build --release --verbose
    #- name: Run tests
    #  run: cargo test --verbose
